---
# TODO create separate yml for setup and for production
- name: Generate filebeat.yml for Filebeat node
  ansible.builtin.template:
    src: "filebeat.yml.j2"
    dest: "{{ filebeat_config }}/config/filebeat.yml"
    group: "root"
    owner: "root"
    mode: "0644"
