---
- name: Copy the certificate for Filebeat
  ansible.builtin.copy:
    content: "{{ item.source }}"
    dest: "{{ filebeat_config }}/certs/{{ item.file }}"
    mode: "0440"
    owner: "1000"
    group: "1000"
  loop:
    - file: http_ca.crt
      source: "{{ xpack_http_ca }}"
    - file: kibana_signing_ca.crt
      source: "{{ server_ssl_ca }}"
  no_log: true
