---
- name: Generate the configuration files of Logstash from templates
  ansible.builtin.template:
    src: "{{ item.source }}"
    dest: "{{ logstash_config }}/{{ item.file }}"
    mode: "0644"
    owner: "{{ owner_uid }}"
    group: "{{ group_uid }}"
  loop:
    - file: "config/logstash.yml"
      source: "logstash.yml.j2"
    - file: "config/pipelines.yml"
      source: "pipelines.yml.j2"

- name: Generate pipeline configs
  ansible.builtin.template:
    src: "{{ item.type }}.conf.j2"
    dest: "{{ logstash_config }}/pipelines/{{ item.name }}_{{ item.id }}.conf"
    mode: "0644"
    owner: "{{ owner_uid }}"
    group: "{{ group_uid }}"
  when: item.enabled
  loop: "{{ logstash_pipelines }}"

- name: Generate log4j2.properties for Logstash node
  ansible.builtin.copy:
    src: "log4j2.properties"
    dest: "{{ logstash_config }}/config/log4j2.properties"
    group: "{{ group_uid }}"
    owner: "{{ owner_uid }}"
    mode: "0644"
