---
- name: Copy certificates to Logstash servers
  ansible.builtin.copy:
    content: "{{ item.source }}"
    dest: "{{ logstash_config }}/certs/{{ item.file }}"
    mode: "0440"
    owner: "{{ owner_uid }}"
    group: "{{ group_uid }}"
  loop:
    - file: http_ca.crt
      source: "{{ xpack_http_ca }}"
    - file: ssl_cert.crt
      source: "{{ logstash_server_ssl_cert }}"
    - file: ssl_cert.key
      source: "{{ logstash_server_ssl_key }}"
  no_log: true
