---
- name: Copy certificates to Logstash servers
  copy:
    content: "{{ item.source }}"
    dest: "{{ logstash_config }}/certs/{{ item.file }}"
    mode: "0440"
    owner: "1000"
    group: "1000"
  loop:
    - file: http_ca.crt
      source: "{{ xpack_http_ca }}"
    - file: ssl_cert.crt
      source: "{{ logstash_server_ssl_cert }}"
    - file: ssl_cert.key
      source: "{{ logstash_server_ssl_key }}"
  no_log: true
