namespace: "abalage"
name: "elasticstack_podman"
description: "Deploying Elasticsearch Stack by using podman pods and containers"
version: "1.0.5"
readme: "README.md"
authors:
    - "Balázs NÉMETH (https://balagetech.com)"
dependencies:
    "containers.podman": ">=1.5.0"
license:
    - "Apache-2.0"
tags:
    - podman
    - elasticsearch
    - kibana
    - metricbeat
    - filebeat
    - logstash
    - monitoring
repository: https://www.github.com/abalage/ansible_collection_elasticstack_podman
issues: https://github.com/abalage/ansible_collection_elasticstack_podman/issues
