---

- name: Create persistent directories for Kibana
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'
  loop:
    - "{{ kibana_config }}/config"
    - "{{ kibana_config }}/certs"
    - "{{ kibana_data }}/logs"
