---
- name: Import createdirs
  ansible.builtin.include_tasks:
    file: "createdirs.yml"
    apply:
      tags: create_dirs
  tags: create_dirs

- name: Include generatetemplates
  ansible.builtin.include_tasks: "generatetemplates.yml"

- name: Include synccerts
  ansible.builtin.include_tasks: synccerts.yml

- name: Include kibana_podman
  ansible.builtin.include_tasks: "kibana_podman.yml"
