---
- name: Copy the certificate used to issue the Elasticsearch node certificates to Kibana servers
  ansible.builtin.copy:
    content: "{{ item.source }}"
    dest: "{{ kibana_config }}/certs/{{ item.file }}"
    mode: "0440"
    owner: "{{ owner_uid }}"
    group: "{{ group_uid }}"
  loop:
    - file: elastic_ca.crt
      source: "{{ elasticsearch_ssl_ca }}"
    - file: kibana_signing_ca.crt
      source: "{{ server_ssl_ca }}"
    - file: ssl.crt
      source: "{{ server_ssl_cert }}"
    - file: ssl.key
      source: "{{ server_ssl_key }}"
    - file: ssl.p12
      source: "{{ server_ssl_keystore }}"
  no_log: true
