---

- name: "Generating metricbeat config and placing into config directory"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ metricbeat_config }}/config/{{ item }}"
    mode: "0644"
    owner: "root"
    group: "root"
  loop:
    - metricbeat.docker.yml
