---

- name: Copy the certificates for Metricbeat
  ansible.builtin.copy:
    content: "{{ item.source }}"
    dest: "{{ metricbeat_config }}/certs/{{ item.file }}"
    mode: "0440"
    owner: "1000"
    group: "1000"
  loop:
    - file: transport_ca.crt
      source: "{{ xpack_transport_ca }}"
    - file: kibana_signing_ca.crt
      source: "{{ server_ssl_ca }}"
  no_log: true
