---
- name: Play for installing the whole stack
  hosts: all
  remote_user: "{{ansible_remote_user}}"
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - role: abalage.elasticstack_podman.elasticsearch
    - role: abalage.elasticstack_podman.kibana
    - role: abalage.elasticstack_podman.filebeat
    - role: abalage.elasticstack_podman.metricbeat
    - role: abalage.elasticstack_podman.logstash

- name: Deploy Elasticsearch hosts
  hosts: elastic_hosts
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - role: abalage.elasticstack_podman.elasticsearch
      tags:
        - elasticsearch
        - elk

- name: Deploy Kibana hosts
  hosts: kibana_hosts
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - role: abalage.elasticstack_podman.kibana
      tags:
        - kibana
        - elk

- name: Deploy Filebeat hosts
  hosts: filebeat_hosts
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - role: abalage.elasticstack_podman.filebeat
      tags:
        - filebeat
        - elk
        - beats

- name: Deploy Metricbeat hosts
  hosts: metricbeat_hosts
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - role: abalage.elasticstack_podman.metricbeat
      tags:
        - metricbeat
        - elk
        - beats

- name: Deploy Logstash hosts
  hosts: logstash_hosts
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - role: abalage.elasticstack_podman.logstash
      tags:
        - logstash
        - elk
