---
# tasks file for elasticsearch

- name: Include task sysctlsetup.yml
  ansible.builtin.include_tasks: "sysctlsetup.yml"

- name: Import createdirs
  ansible.builtin.include_tasks:
    file: "createdirs.yml"
    apply:
      tags: create_dirs
  tags: create_dirs

- name: Include task generatetemplates.yml
  ansible.builtin.include_tasks: "generatetemplates.yml"

- name: Include task synccerts.yml
  ansible.builtin.include_tasks: "synccerts.yml"

# TODO rename this to podman_elasticsearch.yml
- name: Include task elastic_stack_podman.yml
  ansible.builtin.include_tasks: "elastic_stack_podman.yml"

- name: Create roles and users
  tags: security
  run_once: true
  when: not ansible_check_mode
  block:
    # https://www.middlewareinventory.com/blog/ansible-dict/#How_to_append_or_add_elements_into_ansible_dictionary
    - name: Include custom roles from inventory
      ansible.builtin.set_fact:
        es_roles: "{{ es_roles | combine(es_roles_custom, recursive=True) }}"
      when: es_roles_custom is defined

    - name: Include custom users from inventory
      ansible.builtin.set_fact:
        es_users: "{{ es_users | combine(es_users_custom, recursive=True) }}"
      when: es_users_custom is defined

    - name: Wait for Elasticsearch API to be available (timeout 300 sec)
      ansible.builtin.wait_for:
        host: "{{ es_api_host }}"
        port: 9200
        delay: 30
        state: started
        timeout: 300

    - name: Wait for cluster state to be YELLOW or GREEN (timeout 300 sec)
      ansible.builtin.uri:
        url: "{{ es_api_uri }}/_cat/health"
        return_content: true
        validate_certs: "{{ es_validate_certs }}"
        user: "{{ es_api_basic_auth_username }}"
        password: "{{ es_api_basic_auth_password }}"
        force_basic_auth: true
      register: response
      until: "'red' not in response.content and ((response.content.find('yellow') != -1) or (response.content.find('green') != -1))"
      delay: 5
      retries: 60

    - name: Include task elasticsearch-security-native.yml
      ansible.builtin.include_tasks:
        file: "elasticsearch-security-native.yml"
        apply:
          tags: security
