---
- name: Copy the X.509 certificates for transport and http security
  ansible.builtin.copy:
    content: "{{ item.source }}"
    dest: "{{ elastic_config }}/certs/{{ item.file }}"
    mode: "0440"
    owner: "{{ owner_uid }}"
    group: "{{ group_uid }}"
  loop:
    - file: transport_ca.crt
      source: "{{ xpack_transport_ca }}"
    - file: instance.crt
      source: "{{ xpack_transport_ssl_cert }}"
    - file: instance.key
      source: "{{ xpack_transport_ssl_key }}"
    - file: instance.p12
      source: "{{ xpack_transport_ssl_keystore }}"
    - file: http_ca.crt
      source: "{{ xpack_http_ca }}"
    - file: http.crt
      source: "{{ xpack_http_ssl_cert }}"
    - file: http.key
      source: "{{ xpack_http_ssl_key }}"
    - file: http.p12
      source: "{{ xpack_http_ssl_keystore }}"
  no_log: true
